openapi: 3.2.0
info:
  title: ClickFunnels Funnels::Tag API
  termsOfService: https://www.clickfunnels.com/terms-of-service
  contact:
    name: ClickFunnels API Team
    url: https://developers.myclickfunnels.com
  x-logo:
    url: https://statics.myclickfunnels.com/image/1126065/file/31edf05760fafe41a82f16a668ab251f.png
  description: 'The ClickFunnels REST API that powers webhooks, native integrations, and Zapier lets you manage your ClickFunnels data, automate your workflows, and recreate ClickFunnels functionality in your own apps.

    '
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 2.0.0
servers:
- url: https://{subdomain}.myclickfunnels.com/api/v2
  description: ClickFunnels API
  variables:
    subdomain:
      default: myworkspace
security:
- BearerAuth: []
tags:
- name: Funnels::Tag
  description: '> Funnels::Tag are used to distinguish, segment and run additional automations on your funnels and the users who go through them.

    '
paths:
  /workspaces/{workspace_id}/funnels/tags:
    get:
      tags:
      - Funnels::Tag
      summary: List Tags
      description: List Tags
      operationId: listFunnelsTags
      parameters:
      - name: workspace_id
        in: path
        required: true
        schema:
          type: string
      - $ref: '#/components/parameters/after'
      - $ref: '#/components/parameters/sort_order'
      - $ref: '#/components/parameters/sort_property'
      - name: filter
        in: query
        description: 'Filter by available properties in query params, like this: `api/v2/resources?filter[id]=value&filter[another_property]=value1,value2`. Check our Filtering guide for examples and all about filtering [here](https://developers.myclickfunnels.com/docs/filtering).

          '
        required: false
        schema:
          type: object
          properties:
            id:
              type: string
              description: A comma-separated list of funnel tag IDs to filter by.
              example: 1,42
            name:
              type: string
              description: A comma-separated list of funnel tag names to filter by.
              example: cool-funnel,gold
        style: deepObject
        explode: true
      responses:
        '200':
          description: OK
          headers:
            Pagination-Next:
              $ref: '#/components/headers/PaginationNext'
            Link:
              $ref: '#/components/headers/Link'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FunnelsTagAttributes'
              example:
              - id: 13
                public_id: ASRFDJ
                workspace_id: 42000
                name: Example Funnel Tag
                color: '#00FF00'
                created_at: '2025-01-01T00:00:00.000Z'
                updated_at: '2025-01-01T00:00:00.000Z'
              - id: 14
                public_id: BOLSTF
                workspace_id: 42000
                name: Example Funnel Tag
                color: '#00FF00'
                created_at: '2025-01-01T00:00:00.000Z'
                updated_at: '2025-01-01T00:00:00.000Z'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: API key missing or invalid
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Not found - This usually happens when you try to access a record that does not exist in your account. It can also happen when the provided parent record is missing, e.g. you have put in a non-existent Workspaces parent ID.
              example:
                error: 'Not found: Record missing'
    post:
      tags:
      - Funnels::Tag
      summary: Create Tag
      description: Create Tag
      operationId: createFunnelsTags
      parameters:
      - name: workspace_id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        description: Information about a new Tag
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                funnels_tag:
                  type: object
                  $ref: '#/components/schemas/FunnelsTagParameters'
            example:
              funnels_tag:
                name: Example Funnel Tag
                color: '#FF5733'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FunnelsTagAttributes'
              example:
                id: 16
                public_id: kWtTdf
                workspace_id: 42000
                name: Example Funnel Tag
                color: '#00FF00'
                created_at: '2025-01-01T00:00:00.000Z'
                updated_at: '2025-01-01T00:00:00.000Z'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: 'Bad request: HTTP body must be valid JSON'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: API key missing or invalid
  /funnels/tags/{id}:
    get:
      tags:
      - Funnels::Tag
      summary: Fetch Tag
      description: Fetch Tag
      operationId: getFunnelsTags
      parameters:
      - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FunnelsTagAttributes'
              example:
                id: 15
                public_id: JeoWrf
                workspace_id: 42000
                name: Example Funnel Tag
                color: '#00FF00'
                created_at: '2025-01-01T00:00:00.000Z'
                updated_at: '2025-01-01T00:00:00.000Z'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: API key missing or invalid
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: 'Not found: Record missing'
    put:
      tags:
      - Funnels::Tag
      summary: Update Tag
      description: Update Tag
      operationId: updateFunnelsTags
      parameters:
      - $ref: '#/components/parameters/id'
      requestBody:
        description: Information about updated fields in Tag
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                funnels_tag:
                  type: object
                  $ref: '#/components/schemas/FunnelsTagParametersUpdate'
            example:
              funnels_tag:
                name: Example Funnel Tag
                color: '#FF5733'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FunnelsTagAttributes'
              example:
                id: 18
                public_id: tipucD
                workspace_id: 42000
                name: Example Funnel Tag
                color: '#00FF00'
                created_at: '2025-01-01T00:00:00.000Z'
                updated_at: '2025-01-01T00:00:00.000Z'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: 'Bad request: HTTP body must be valid JSON'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: API key missing or invalid
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: 'Not found: Record missing'
    delete:
      tags:
      - Funnels::Tag
      summary: Remove Tag
      description: Remove Tag
      operationId: removeFunnelsTags
      parameters:
      - $ref: '#/components/parameters/id'
      responses:
        '204':
          description: No Content
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: API key missing or invalid
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: 'Not found: Record missing'
components:
  parameters:
    id:
      name: id
      in: path
      required: true
      schema:
        type: string
    sort_property:
      name: sort_property
      in: query
      description: 'Sort property of a list response. The default is id and thus the created_at order.

        If you sort by other properties, we additionally sort by id implicitly as a secondary sort property, so that you can rely on the sort order to be deterministic even if the main sort property ends up with the same values.

        '
      required: false
      schema:
        type: string
        enum:
        - id
        - updated_at
    sort_order:
      name: sort_order
      in: query
      description: Sort order of a list response. Use 'desc' to reverse the default 'asc' (ascending) sort order. Examples [in our guides](https://developers.myclickfunnels.com/docs/pagination).
      required: false
      schema:
        type: string
        enum:
        - asc
        - desc
    after:
      name: after
      in: query
      required: false
      schema:
        type: string
      description: ID of item after which the collection should be returned. More examples and info about pagination [in our guides](https://developers.myclickfunnels.com/docs/pagination).
  schemas:
    FunnelsTagParameters:
      type: object
      title: Funnel Tags
      description: Funnel Tags
      required:
      - name
      properties:
        name:
          type: string
          description: The name of the funnel tag
        color:
          type: string
          description: The color of the funnel tag
      example:
        funnels_tag:
          name: Example Funnel Tag
          color: '#FF5733'
    FunnelsTagAttributes:
      type: object
      title: Funnel Tags
      description: Funnel Tags
      properties:
        id:
          type: integer
          description: ID
        public_id:
          type:
          - string
          - 'null'
          description: Public ID
        workspace_id:
          type: integer
          description: Workspace ID
        name:
          type: string
          description: The name of the funnel tag
        color:
          type: string
          description: The color of the funnel tag
        created_at:
          type:
          - string
          - 'null'
          format: date-time
          description: Created at
        updated_at:
          type:
          - string
          - 'null'
          format: date-time
          description: Updated at
      example:
        id: 2
        public_id: izTPVd
        workspace_id: 42000
        name: Example Funnel Tag
        color: '#00FF00'
        created_at: '2025-01-01T00:00:00.000Z'
        updated_at: '2025-01-01T00:00:00.000Z'
      required:
      - color
      - created_at
      - id
      - name
      - public_id
      - updated_at
      - workspace_id
    FunnelsTagParametersUpdate:
      type: object
      title: Funnel Tags
      description: Funnel Tags
      required: []
      properties:
        name:
          type: string
          description: Name of the funnel tag
        color:
          type: string
          description: The color of the funnel tag
      example:
        funnels_tag:
          name: Example Funnel Tag
          color: '#FF5733'
  headers:
    Link:
      description: A direct link to the next page for the cursor-based pagination. It includes the `after` and the Pagination-Next ID value.
      schema:
        type: string
    PaginationNext:
      description: ID of the last item in the current response after which more records exist. You can use it in an `after` query parameter for cursor-based pagination to get to the next page.
      schema:
        type: string
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
externalDocs:
  description: More in-depth guides and further resources
  url: https://developers.myclickfunnels.com
